### ISSUE TITLE
xfce dotfiles

### ISSUE THREAD

**Issue by mrlinuxdude** [ahmadhabibi14/hyprland-dots#1]
i follow you fb group. was wodnering if you still have xfce dots

Thanks

**Comment by ahmadhabibi14** [comment]
Yeah, I still have xfce dots, but it's a bit messy 😅

**Comment by mrlinuxdude** [comment]
when you get chance let know link. too them

**Comment by ahmadhabibi14** [comment]
You mean this one ? https://github.com/ahmadhabibi14/dotfile

**Comment by mrlinuxdude** [comment]
Thanks i love it...amazing
